// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebEssentials
{
    internal sealed partial class Vsix
    {
        public const string Id = "509fc133-d9a6-4cf7-a558-e00fd11e0f9f";
        public const string Name = "Web Essentials 2019";
        public const string Description = @"The easiest way to set up Visual Studio for the ultimate web development experience.";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Mads Kristensen";
        public const string Tags = "extensions, vsix, install";
    }
}
